name: Build Paid

on:
    push:
        branches:
          - 'paid'
        tags:
            - 'v*.*.*-paid-.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
    build:
        name: Build Paid
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Setup Environment
              run: node -e "console.log('PACKAGE_VERSION=' + require('./package.json').version + '\nPACKAGE_NAME=' + require('./package.json').name + '-' + require('./package.json').version)" >> $GITHUB_ENV
            - name: Install
              run: pnpm install
            - name: Package extension
              run: pnpm run package
            - name: Create GitHub release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  name: v${{ env.PACKAGE_VERSION }}
                  draft: false
                  prerelease: false
                  files: ./${{ env.PACKAGE_NAME }}.vsix
